server:
  port: 8092
#?????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.222.128:3306/dlyk?useSSL=false&charset=utf8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  data:
    redis:
      port: 6379
      host: 192.168.222.128
      password: 123456
      database: 0
mybatis:
  mapper-locations: classpath:/mappers/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
